/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
/**
 * Defines values for UserAssignedIdentities.
 * Possible values include: 'Microsoft.ManagedIdentity/userAssignedIdentities'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: UserAssignedIdentities =
 * <UserAssignedIdentities>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export var UserAssignedIdentities;
(function (UserAssignedIdentities) {
    UserAssignedIdentities["MicrosoftManagedIdentityuserAssignedIdentities"] = "Microsoft.ManagedIdentity/userAssignedIdentities";
})(UserAssignedIdentities || (UserAssignedIdentities = {}));
//# sourceMappingURL=index.js.map