/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as tslib_1 from "tslib";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { ManagedServiceIdentityClientContext } from "./managedServiceIdentityClientContext";
var ManagedServiceIdentityClient = /** @class */ (function (_super) {
    tslib_1.__extends(ManagedServiceIdentityClient, _super);
    /**
     * Initializes a new instance of the ManagedServiceIdentityClient class.
     * @param credentials Credentials needed for the client to connect to Azure.
     * @param subscriptionId The Id of the Subscription to which the identity belongs.
     * @param [options] The parameter options
     */
    function ManagedServiceIdentityClient(credentials, subscriptionId, options) {
        var _this = _super.call(this, credentials, subscriptionId, options) || this;
        _this.operations = new operations.Operations(_this);
        _this.userAssignedIdentities = new operations.UserAssignedIdentities(_this);
        return _this;
    }
    return ManagedServiceIdentityClient;
}(ManagedServiceIdentityClientContext));
// Operation Specifications
export { ManagedServiceIdentityClient, ManagedServiceIdentityClientContext, Models as ManagedServiceIdentityModels, Mappers as ManagedServiceIdentityMappers };
export * from "./operations";
//# sourceMappingURL=managedServiceIdentityClient.js.map