/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
export var acceptLanguage = {
    parameterPath: "acceptLanguage",
    mapper: {
        serializedName: "accept-language",
        defaultValue: 'en-US',
        type: {
            name: "String"
        }
    }
};
export var apiVersion0 = {
    parameterPath: "apiVersion",
    mapper: {
        required: true,
        isConstant: true,
        serializedName: "api-version",
        defaultValue: '2015-06-01',
        type: {
            name: "String"
        }
    }
};
export var apiVersion1 = {
    parameterPath: "apiVersion",
    mapper: {
        required: true,
        isConstant: true,
        serializedName: "api-version",
        defaultValue: '2018-01-01-preview',
        type: {
            name: "String"
        }
    }
};
export var apiVersion2 = {
    parameterPath: "apiVersion",
    mapper: {
        required: true,
        isConstant: true,
        serializedName: "api-version",
        defaultValue: '2018-07-01-preview',
        type: {
            name: "String"
        }
    }
};
export var denyAssignmentId0 = {
    parameterPath: "denyAssignmentId",
    mapper: {
        required: true,
        serializedName: "denyAssignmentId",
        type: {
            name: "String"
        }
    }
};
export var denyAssignmentId1 = {
    parameterPath: "denyAssignmentId",
    mapper: {
        required: true,
        serializedName: "denyAssignmentId",
        type: {
            name: "String"
        }
    },
    skipEncoding: true
};
export var expand = {
    parameterPath: [
        "options",
        "expand"
    ],
    mapper: {
        serializedName: "$expand",
        defaultValue: 'resourceTypes',
        type: {
            name: "String"
        }
    }
};
export var filter = {
    parameterPath: [
        "options",
        "filter"
    ],
    mapper: {
        serializedName: "$filter",
        type: {
            name: "String"
        }
    }
};
export var nextPageLink = {
    parameterPath: "nextPageLink",
    mapper: {
        required: true,
        serializedName: "nextLink",
        type: {
            name: "String"
        }
    },
    skipEncoding: true
};
export var parentResourcePath = {
    parameterPath: "parentResourcePath",
    mapper: {
        required: true,
        serializedName: "parentResourcePath",
        type: {
            name: "String"
        }
    },
    skipEncoding: true
};
export var resourceGroupName = {
    parameterPath: "resourceGroupName",
    mapper: {
        required: true,
        serializedName: "resourceGroupName",
        type: {
            name: "String"
        }
    }
};
export var resourceName = {
    parameterPath: "resourceName",
    mapper: {
        required: true,
        serializedName: "resourceName",
        type: {
            name: "String"
        }
    }
};
export var resourceProviderNamespace = {
    parameterPath: "resourceProviderNamespace",
    mapper: {
        required: true,
        serializedName: "resourceProviderNamespace",
        type: {
            name: "String"
        }
    }
};
export var resourceType = {
    parameterPath: "resourceType",
    mapper: {
        required: true,
        serializedName: "resourceType",
        type: {
            name: "String"
        }
    },
    skipEncoding: true
};
export var roleAssignmentName = {
    parameterPath: "roleAssignmentName",
    mapper: {
        required: true,
        serializedName: "roleAssignmentName",
        type: {
            name: "String"
        }
    }
};
export var roleDefinitionId = {
    parameterPath: "roleDefinitionId",
    mapper: {
        required: true,
        serializedName: "roleDefinitionId",
        type: {
            name: "String"
        }
    }
};
export var roleId = {
    parameterPath: "roleId",
    mapper: {
        required: true,
        serializedName: "roleId",
        type: {
            name: "String"
        }
    },
    skipEncoding: true
};
export var scope = {
    parameterPath: "scope",
    mapper: {
        required: true,
        serializedName: "scope",
        type: {
            name: "String"
        }
    },
    skipEncoding: true
};
export var subscriptionId = {
    parameterPath: "subscriptionId",
    mapper: {
        required: true,
        serializedName: "subscriptionId",
        type: {
            name: "String"
        }
    }
};
//# sourceMappingURL=parameters.js.map