/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as msRest from "ms-rest-js";
import * as Mappers from "../models/tagsMappers";
import * as Parameters from "../models/parameters";
/** Class representing a Tags. */
var Tags = /** @class */ (function () {
    /**
     * Create a Tags.
     * @param {ResourceManagementClientContext} client Reference to the service client.
     */
    function Tags(client) {
        this.client = client;
    }
    Tags.prototype.deleteValue = function (tagName, tagValue, options, callback) {
        return this.client.sendOperationRequest({
            tagName: tagName,
            tagValue: tagValue,
            options: options
        }, deleteValueOperationSpec, callback);
    };
    Tags.prototype.createOrUpdateValue = function (tagName, tagValue, options, callback) {
        return this.client.sendOperationRequest({
            tagName: tagName,
            tagValue: tagValue,
            options: options
        }, createOrUpdateValueOperationSpec, callback);
    };
    Tags.prototype.createOrUpdate = function (tagName, options, callback) {
        return this.client.sendOperationRequest({
            tagName: tagName,
            options: options
        }, createOrUpdateOperationSpec, callback);
    };
    Tags.prototype.deleteMethod = function (tagName, options, callback) {
        return this.client.sendOperationRequest({
            tagName: tagName,
            options: options
        }, deleteMethodOperationSpec, callback);
    };
    Tags.prototype.list = function (options, callback) {
        return this.client.sendOperationRequest({
            options: options
        }, listOperationSpec, callback);
    };
    Tags.prototype.listNext = function (nextPageLink, options, callback) {
        return this.client.sendOperationRequest({
            nextPageLink: nextPageLink,
            options: options
        }, listNextOperationSpec, callback);
    };
    return Tags;
}());
export { Tags };
// Operation Specifications
var serializer = new msRest.Serializer(Mappers);
var deleteValueOperationSpec = {
    httpMethod: "DELETE",
    path: "subscriptions/{subscriptionId}/tagNames/{tagName}/tagValues/{tagValue}",
    urlParameters: [
        Parameters.tagName,
        Parameters.tagValue,
        Parameters.subscriptionId
    ],
    queryParameters: [
        Parameters.apiVersion
    ],
    headerParameters: [
        Parameters.acceptLanguage
    ],
    responses: {
        200: {},
        204: {},
        default: {
            bodyMapper: Mappers.CloudError
        }
    },
    serializer: serializer
};
var createOrUpdateValueOperationSpec = {
    httpMethod: "PUT",
    path: "subscriptions/{subscriptionId}/tagNames/{tagName}/tagValues/{tagValue}",
    urlParameters: [
        Parameters.tagName,
        Parameters.tagValue,
        Parameters.subscriptionId
    ],
    queryParameters: [
        Parameters.apiVersion
    ],
    headerParameters: [
        Parameters.acceptLanguage
    ],
    responses: {
        200: {
            bodyMapper: Mappers.TagValue
        },
        201: {
            bodyMapper: Mappers.TagValue
        },
        default: {
            bodyMapper: Mappers.CloudError
        }
    },
    serializer: serializer
};
var createOrUpdateOperationSpec = {
    httpMethod: "PUT",
    path: "subscriptions/{subscriptionId}/tagNames/{tagName}",
    urlParameters: [
        Parameters.tagName,
        Parameters.subscriptionId
    ],
    queryParameters: [
        Parameters.apiVersion
    ],
    headerParameters: [
        Parameters.acceptLanguage
    ],
    responses: {
        200: {
            bodyMapper: Mappers.TagDetails
        },
        201: {
            bodyMapper: Mappers.TagDetails
        },
        default: {
            bodyMapper: Mappers.CloudError
        }
    },
    serializer: serializer
};
var deleteMethodOperationSpec = {
    httpMethod: "DELETE",
    path: "subscriptions/{subscriptionId}/tagNames/{tagName}",
    urlParameters: [
        Parameters.tagName,
        Parameters.subscriptionId
    ],
    queryParameters: [
        Parameters.apiVersion
    ],
    headerParameters: [
        Parameters.acceptLanguage
    ],
    responses: {
        200: {},
        204: {},
        default: {
            bodyMapper: Mappers.CloudError
        }
    },
    serializer: serializer
};
var listOperationSpec = {
    httpMethod: "GET",
    path: "subscriptions/{subscriptionId}/tagNames",
    urlParameters: [
        Parameters.subscriptionId
    ],
    queryParameters: [
        Parameters.apiVersion
    ],
    headerParameters: [
        Parameters.acceptLanguage
    ],
    responses: {
        200: {
            bodyMapper: Mappers.TagsListResult
        },
        default: {
            bodyMapper: Mappers.CloudError
        }
    },
    serializer: serializer
};
var listNextOperationSpec = {
    httpMethod: "GET",
    baseUrl: "https://management.azure.com",
    path: "{nextLink}",
    urlParameters: [
        Parameters.nextPageLink
    ],
    headerParameters: [
        Parameters.acceptLanguage
    ],
    responses: {
        200: {
            bodyMapper: Mappers.TagsListResult
        },
        default: {
            bodyMapper: Mappers.CloudError
        }
    },
    serializer: serializer
};
//# sourceMappingURL=tags.js.map